### ISSUE TITLE
NASBench201 KeyError

### ISSUE THREAD

**Issue by zhaohui-yang** [D-X-Y/AutoDL-Projects#81]
Thanks for sharing the great repo. I tried to access the accuracy of 'x-valid' on CIFAR10 dataset but failed because of the key error.

```
>>> results = api.query_by_index(0, 'cifar10')
>>> results.keys()
dict_keys([777, 888, 999])
>>> results[888].get_eval('x-valid')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangzhaohui/anaconda3/lib/python3.7/site-packages/nas_201_api/api.py", line 885, in get_eval
    'loss'    : self.eval_losses['{:}@{:}'.format(name,iepoch)],
KeyError: 'x-valid@199'
```

**Comment by D-X-Y** [comment]
I will have a look at this problem today and get back to you soon.

**Comment by zhaohui-yang** [comment]
ok, waiting for you.

**Comment by D-X-Y** [comment]
To access the validation information, please use:
```
results = api.query_by_index(0, 'cifar10-valid')
results[888].get_eval('x-valid')
```

**Comment by zhaohui-yang** [comment]
Problem solved, thank you!

```
train -> results[key].get_train()['accuracy']
cifar10-valid -> results[key].get_eval('x-valid'/'ori-test')['accuracy']
```

**Comment by D-X-Y** [comment]
You are welcome!

**Comment by zhaohui-yang** [comment]
It's a great work and everyone should use the benchmark to verify their search algorithm!
